language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6

matrix:
  fast_finish: true
  include:
      - php: 5.6
        env: ECCUBE_VERSION=3.0.8
      - php: 5.6
        env: ECCUBE_VERSION=3.0.9

before_script:
  - tar cvzf $HOME/plugin.tar.gz ./*
  - git clone https://github.com/EC-CUBE/ec-cube.git
  - cd ec-cube
  - git checkout -b ${ECCUBE_VERSION} refs/tags/${ECCUBE_VERSION}
  - composer selfupdate
  - composer install --dev --no-interaction -o
  - sh ./eccube_install.sh sqlite3 none
  - php app/console plugin:develop install --path=$HOME/plugin.tar.gz

#script:
#  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpunit --coverage-clover=coverage.clover ; fi
#  - if [[ $TRAVIS_PHP_VERSION =~ ^[57] ]]; then phpunit ; fi

