language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
#  - 5.3
#  - 5.4
  - 5.5
  - 5.6
#  - 7.0

env:
  - ECCUBE_VERSION=3.0.8
  - ECCUBE_VERSION=3.0.9

matrix:
  fast_finish: true

before_script:
  - tar cvzf $HOME/plugin.tar.gz ./*
  - git clone https://github.com/EC-CUBE/ec-cube.git
  - cd ec-cube
  - git checkout -b ${ECCUBE_VERSION} refs/tags/${ECCUBE_VERSION}
  - composer selfupdate
  - composer install --dev --no-interaction -o
  - sh eccube_install.sh sqlite3 none
  - php app/console plugin:develop install --path=$HOME/plugin.tar.gz
  - cd ../

#script:
#  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpunit --coverage-clover=coverage.clover ; fi
#  - if [[ $TRAVIS_PHP_VERSION =~ ^[57] ]]; then phpunit ; fi

